ini_write_real("Save", "spr_beard_normal", 1);
ini_write_real("Save", "spr_beard_chops", 0);
ini_write_real("Save", "spr_beard_black", 0);
ini_write_real("Save", "spr_abe", 0);
ini_write_real("Save", "spr_chaplin", 0);
ini_write_real("Save", "spr_chops_2", 0);
ini_write_real("Save", "spr_grey", 0);
ini_write_real("Save", "spr_white", 0);
ini_write_real("Save", "spr_van_dyke", 0);